#!/usr/bin/env python3

import openai, os, sys, time, gammu, mysql.connector

# Connect to the whitelist database SQL
conn = mysql.connector.connect(host="YOUR HOST",
                               user="YOUR USER", password="YOUR PASSWD", 
                               database="whitelist")

# Create a cursor
cur = conn.cursor()

# Execute a query
query = "SELECT phone_number FROM whitelist"
cur.execute(query)

# Fetch the result
result = cur.fetchall()

# Convert tuples to a list for later use
result = [r[0] for r in result]

# Set variables for message receiver and recipient
recipient = os.environ['SMS_1_NUMBER']
message_received = os.environ['SMS_1_TEXT']
response = ""

# Messages for gammu logs
print("SYSTEM: Message received from " + recipient + " : " + message_received)

# Set up the OpenAI API client
openai.api_key = "YOUR API KEY"

# Set up the model and prompt
model_engine = "text-davinci-003"

if recipient in result:

# Generate a response: 
    completion = openai.Completion.create(
    	engine=model_engine,
    	prompt=str(message_received),
    	max_tokens=1024,
    	n=1,
    	stop=None,
    	temperature=0.5,
    )

    response = completion.choices[0].text

# To remove the 2 "Enter" characters in front of the message and add symbols "" for str()
    response = '"' + response[2:] + '"'

# Send the message generated by AI to the number that sent you a request
    os.system('echo ' + str(response) + ' | sudo gammu sendsms TEXT ' + str(recipient) + " -autolen 99999")
    print("SYSTEM: Message sent :\n" + str(response))

else:

# Send nothing to people who aren't whitelisted
    print("SYSTEM: Recipient not whitelisted")
    print("SYSTEM: No command was executed.")

# Close the cursor and connection
cur.close()
